### ISSUE TITLE
How to call tree operator

### ISSUE THREAD

**Issue by BowenRaymone** [ropensci/beastier#54]
Hi, 

babette and beastier are really useful packages. But how can I easily call the tree operators (like narrow exchange, wide exchange, Wilson Balding and subtree slide) using these packages? For example, I hope to input a tree, and want to use the package to conduct any of the above mentioned tree operator to my input tree.

Thanks for your attention!

**Comment by richelbilderbeek** [comment]
Hi @BowenRaymone,

> But how can I easily call the tree operators (like narrow exchange, wide exchange, Wilson Balding and subtree slide) using these packages?

That is an interesting question! Short answer is: you cannot.

However, I would be open to allow to do so! I will need a volunteer (you!) to ask dumb questions to and to test things out. Also, if it is an academic paper you are writing, I also volunteer (or is that just work?) to be a minor co-author and describe babette and its workings.

**Comment by richelbilderbeek** [comment]
@BowenRaymone I will close this Issue, as I have gotten no response. Thanks for the question :+1:
