### ISSUE TITLE
Fix: CRAN package beastier -- policy violation

### ISSUE THREAD

**Issue by richelbilderbeek** [ropensci/beastier#58]
From prof Ripley:

install_beast() writes to ~/.local/share and leaves behind a 8MB file BEAST.v2.6.0.Linux.tgz and a 11MB directory beast.  That does not comply with CRAN policy as you warranted (and the locations given by rappdirs do not comply).

It is run by R CMD check --as-cran mcbette.

It seems we need to remind you

<quote>
Packages should not write in the user’s home filespace (including clipboards), nor anywhere else on the file system apart from the R session’s temporary directory (or during installation in the location pointed to by TMPDIR: and such usage should be cleaned up). Installing into the system’s R installation (e.g., scripts to its bin directory) is not allowed.

Limited exceptions may be allowed in interactive sessions if the package obtains confirmation from the user.

For R version 4.0 or later (hence a version dependency is required or only conditional use is possible), packages may store user-specific data, configuration and cache files in their respective user directories obtained from tools::R_user_dir(), provided that by default sizes are kept as small as possible and the contents are actively managed (including removing outdated material).
</quote>

"The time of the volunteers is CRAN’s most precious resource"

and we have better things to do than sweep up after you.

Please correct before 2021-05-26 to retain your package on CRAN.

**Comment by richelbilderbeek** [comment]
I was unaware that rappdirs was forbidden as well.

It feels that the only solution is to replace the install_beast2 function by -say- a text that the user needs to run to install BEAST2 :confused;

**Comment by richelbilderbeek** [comment]
No workaround, I am working to fix this ASAP :rainbow:

**Comment by richelbilderbeek** [comment]
Done this one!

**Comment by thijsjanzen** [comment]
Awesome! (sorry for the belated reply).

It seems thus that mauricer and babette could re-appear on CRAN?

**Comment by richelbilderbeek** [comment]
@thijsjanzen yes indeed, although there will be a new beastier release first. mauricer seems done and babette may be done as well. So, nearly there!

**Comment by thijsjanzen** [comment]
Awesome! Looking forward to the new beastier release!
