### ISSUE TITLE
Test failure on Windows release

### ISSUE THREAD

**Issue by maelle** [ropensci/beastier#62]
```
  Running 'testthat.R'
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  `check_can_create_file("/root_usually_fails")` did not throw an error.
  -- Failure (test-check_can_create_screenlog_file.R:36:3): use ------------------
  `check_can_create_screenlog_file(beast2_options)` did not throw an error.
  -- Failure (test-check_can_create_state_output_file.R:10:3): use impossible folder --
  `check_can_create_state_output_file(beast2_options = create_beast2_options(output_state_filename = "/cannot_work.xml.state"))` did not throw an error.
  -- Failure (test-check_can_create_tracelog_file.R:35:3): use -------------------
  `check_can_create_tracelog_file(beast2_options)` did not throw an error.
  -- Failure (test-check_can_create_treelog_file.R:35:3): use --------------------
  `check_can_create_treelog_file(beast2_options)` did not throw an error.
  -- Failure (test-extract_screenlog_filename_from_beast2_input_file.R:39:3): use --
  `check_can_create_screenlog_file(beast2_options)` did not throw an error.
  
  [ FAIL 7 | WARN 0 | SKIP 7 | PASS 910 ]
  Error: Test failures
  ``` 
  
  See https://github.com/r-universe/ropensci/runs/4938445331?check_suite_focus=true via https://ropensci.r-universe.dev/ui#builds

Happy to help if needed!

**Comment by richelbilderbeek** [comment]
I will take a look this Saturday, thanks @maelle for keeping my packages in good shape!

**Comment by richelbilderbeek** [comment]
That build is great: it seems to be an actual Windows build! Jeroen Ooms keeps amazing :-)

**Comment by maelle** [comment]
For more context on R-universe see https://ropensci.org/r-universe/ :smile_cat:

**Comment by richelbilderbeek** [comment]
One day late, I think I fixed this, let's await the build of this repo :-)

**Comment by richelbilderbeek** [comment]
Hi @maelle, as far as I can see, the build should be fine now. If not, please let me know :-) !

**Comment by maelle** [comment]
:wave: @richelbilderbeek! Thank you! It seems it didn't work though see https://ropensci.r-universe.dev/ui#builds (if you hover on the version number you'll see the last commit of your repo has been built)

Why not use a skip function in the test rather than the return? See https://testthat.r-lib.org/articles/skipping.html

**Comment by richelbilderbeek** [comment]
Hi @maelle, thanks for checking up on me! It should be fixed now.

> Why not use a skip function in the test rather than the return? See https://testthat.r-lib.org/articles/skipping.html

Thanks for the fun question! I am aware of using `skip` and I use both `skip` and `return`. I use `skip` when I care about being reminded I skipped something (e.g. on a test connected to an Issue), as the `skip` text (e.g. for `skip("Issue #42")`, this will be `Issue #42`) appears in the R CMD CHECK log. I use `return` when I don't want to see the test in that log.

`skip_on_os` is new to me, however, maybe I should use it in the future, thanks for sending that testthat link :-)
